name: Generate SDKs

on:
  workflow_dispatch: # Allows manual triggering
  repository_dispatch:
    types: [generate-sdks]

jobs:
  generate_sdks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download kandji_openapi.yaml from latest release
        env:
          GH_TOKEN: ${{ secrets.KANDJI_POSTMAN_TO_OPENAPI_TOKEN }}
        run: |
          gh release download \
            --repo "MScottBlake/kandji-postman-to-openapi" \
            --pattern "kandji_openapi\.yaml" \
            --output "kandji_openapi.yaml"
          echo "openapi_file=kandji_openapi.yaml" >> ${GITHUB_ENV}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openapi_file
          path: ${{ env.openapi_file }}

      - name: Set up OpenAPI Generator
        run: |
          # Define languages to generate SDKs for
          languages=("bash" "go" "javascript" "python" "python-pydantic-v1"  "ruby" "rust" "swift5" "swift6" "typescript-node")
          for lang in "${languages[@]}"; do
            # Create output directory for each language
            mkdir -p "sdks/${lang}"

            # Run OpenAPI Generator
            docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:latest generate \
              -i /local/${{ env.openapi_file}} \
              -g "${lang}" \
              -o "sdks/${lang}"
          done

      - name: Commit and Push to GitHub
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add sdks
          if git diff --quiet; then
            echo "No changes detected"
          else
            git commit -m "Automated SDK update for latest OpenAPI release"
            git push
          fi

      - name: Create GitHub Release
        if: success()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="sdk-update-$(date +'%Y%m%d%H%M%S')"
          gh release create "${tag}" sdks/**/* \
            --title "Automated SDK Update $(date +'%Y-%m-%d %H:%M:%S')" \
            --generate-notes \
            --latest
